services:
#---------------------ticket voter
    app.ticket_voter:
        class: Dreamlex\TicketBundle\Security\Authorization\Voter\TicketVoter
        arguments: ["@security.access.decision_manager"]
        public: false
        tags:
            - { name: security.voter }
        # small performance boost
        public: false

#mapping listner
    dreamlex_ticket.listner:
        class: Dreamlex\TicketBundle\EventListner\LoadMetadata
        arguments:
            - %dreamlex_ticket.user.class%
            - %dreamlex_ticket.user.primary_key%
            - %dreamlex_ticket.user.media_entity%
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

#----------------------admin interface
    dreamlex_ticket.admin.category:
        class: Dreamlex\TicketBundle\Admin\CategoryAdmin
        arguments:
            - ~
            - Dreamlex\TicketBundle\Entity\Category
            - "PixSortableBehaviorBundle:SortableAdmin"
        calls:
            - [ setTranslationDomain, ['admin']] # //TODO убрать или оставить перевод админки
            - [ setPositionService, ["@pix_sortable_behavior.position"]]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Tickets, label: Category }

    dreamlex_ticket.admin.ticket:
        class: Dreamlex\TicketBundle\Admin\TicketAdmin
        arguments: [~, Dreamlex\TicketBundle\Entity\Ticket, DreamlexTicketBundle:TicketAdmin]
        calls:
            - [ addChild, ["@dreamlex_ticket.admin.message"]]
            - [ setTemplate, [list, DreamlexTicketBundle:Admin:list_rows.html.twig]]
            - [ setTokenStorage, ["@security.token_storage"] ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Tickets, label: Ticket }

    dreamlex_ticket.admin.message:
        class: Dreamlex\TicketBundle\Admin\MessageAdmin
        arguments: [~, Dreamlex\TicketBundle\Entity\Message, DreamlexTicketBundle:MessageAdmin]
        calls:
            - [ setTokenStorage, ["@security.token_storage"] ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Tickets, label: Message, show_in_dashboard: false  }
#media provider
    sonata.media.provider.ticket_image:
        class: Dreamlex\TicketBundle\Provider\TicketImageProvider
        arguments:
            - sonata.media.provider.ticket_image
            - "@sonata.media.filesystem.local"
            - "@sonata.media.cdn.server"
            - "@sonata.media.generator.default"
            - "@sonata.media.thumbnail.format"
            - ['jpg', 'png', 'jpeg']
            - ['image/pjpeg', 'image/jpeg', 'image/png', 'image/x-png']
            - "@sonata.media.adapter.image.gd"
            - "@sonata.media.metadata.proxy"
        calls:
            - [ setResizer, ["@sonata.media.resizer.simple"] ]
            - [ setRouter, ["@router.default"] ]
            - [ setTemplates, [ { helper_thumbnail: DreamlexTicketBundle:Provider:thumbnail.html.twig, helper_view: DreamlexTicketBundle:Provider:view_image.html.twig } ] ]
        tags:
            - { name: sonata.media.provider }
#media type
    file.media.type:
        class: Dreamlex\TicketBundle\Form\Type\FileMediaType
        arguments:
            - '@sonata.media.pool'
            - %dreamlex_ticket.user.media_entity%
        tags:
            - { name: form.type }
#form handlers
    dreamlex_ticket.show_form_handler:
        class: Dreamlex\TicketBundle\Form\Handler\TicketShowFormHandler
        arguments:
            - "@dreamlex_ticket.ticket_manager"

    dreamlex_ticket.create_form_handler:
        class: Dreamlex\TicketBundle\Form\Handler\TicketCreateFormHandler
        arguments:
            - "@dreamlex_ticket.ticket_manager"
#entity managers
    dreamlex_ticket.ticket_manager:
        class: Dreamlex\TicketBundle\Entity\Manager\TicketManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"
            - "@dreamlex_ticket.message_manager"

    dreamlex_ticket.message_manager:
        class: Dreamlex\TicketBundle\Entity\Manager\MessageManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@security.token_storage"


